### PR TITLE
Better web support check

### PR DESCRIPTION
**Pull request by SimonIT**
This works now also in firefox which doesn't support password credentials
https://developer.mozilla.org/en-US/docs/Web/API/PasswordCredential#browser_compatibility

### CODE REVIEW

**Comment by rekire** [comment]
Interesting. It seems that there is no active development for this feature:
https://bugzilla.mozilla.org/show_bug.cgi?id=1156047

**Comment by rekire** [comment]
I just checked the mdn: I would guess that this api could be used: https://developer.mozilla.org/en-US/docs/Web/API/CredentialsContainer/store

However I think you have more experience with that. So the question is now better to use PasswordCredential or CredentialsContainer.

**Comment by SimonIT** [comment]
I think you misunderstood something.
If you look at the example, the `store` method of the `CredentialsContainer` takes the `PasswordCredential` object which has the values for the password and the username.
If you want, I can setup a github action which delpoys the example as web part to github pages for a nicer showcase

**Comment by rekire** [comment]
Oh that is a bit confusing, why did the Mozilla guys just implement a part of that Standard? I think that GitHub page preview would be a great to get an impression how this will look in your own app.

**Pull request merged**
